name: Convert Emby JSON to SRS

on:
  push:
    paths:
      - 'sing-box-ruleset/emby.json'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Setup sing-box
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
        echo "Latest sing-box version: $LATEST_VERSION"
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_VERSION}/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Convert JSON to SRS
      run: |
        sing-box rule-set compile --output sing-box-ruleset/emby.srs sing-box-ruleset/emby.json

    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add sing-box-ruleset/emby.srs
        git commit -m "Convert emby.json to emby.srs" || echo "No changes to commit"
        git push
