name: Update emby Rule

on: 
  schedule:
    - cron: '0 1,9,17 * * *'
  workflow_dispatch:

env:
  TZ: Asia/Shanghai
  
jobs:
  update-emby-rule:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        sudo apt-get update
        sudo apt-get install -y jq
  
    - name: Sort emby.json content
      run: |
        # 读取JSON文件并按字母排序后重写
        jq -S '.' emby.json > emby_sorted.json
        mv emby_sorted.json emby.json
        
    - name: Debug emby.json format
      run: |
        # 检查 emby.json 的格式，确保文件是有效的 JSON 格式
        jq . emby.json

    - name: Setup sing-box (release)
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
        echo "Latest sing-box version: $LATEST_VERSION"
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_VERSION}/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Remove old emby.srs
      run: |
        # 删除旧的 emby.srs，确保重新生成
        rm -f emby.srs

    - name: Compile emby.json to emby.srs
      run: |
        # 编译 emby.json 为 emby.srs
        sing-box rule-set compile --output emby.srs emby.json
        # 检查 emby.srs 是否成功生成
        if [ ! -f "emby.srs" ]; then
          echo "Failed to generate emby.srs" >&2
          exit 1
        fi

    - name: Debug emby.srs
      run: |
        # 输出 emby.srs 文件内容，确保文件生成正常
        cat emby.srs

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        # 强制添加 emby.srs 并提交更改
        git add -f emby.srs
        git commit -m "Update emby.srs" || echo "No changes to commit"
        git push
