name: Update emby Rule

on:
  schedule:
    - cron: '0 1,9,17 * * *'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install jq
      run: sudo apt-get update && sudo apt-get install -y jq

    - name: Sort and format emby.json
      run: |
        jq '
          .rules[] |= 
          if has("domain_suffix") then
            .domain_suffix |= sort
          else
            .
          end
        ' emby.json > sorted_emby.json
        
        jq . sorted_emby.json > formatted_emby.json
        mv formatted_emby.json emby.json

    - name: Setup sing-box
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
        echo "Latest sing-box version: $LATEST_VERSION"
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_VERSION}/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Validate JSON format
      run: |
        jq . emby.json > formatted_emby.json
        mv formatted_emby.json emby.json

    - name: Convert emby.json to emby.srs
      run: |
        sing-box rule-set compile --output emby.srs emby.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add emby.json emby.srs
        git commit -m "Update emby rules" || echo "No changes to commit"
        git push
