name: Convert Emby JSON and AdGuard filters to SRS and JSON
on:
  push:
    paths:
      - 'emby.json'
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * *"
permissions:
  contents: write
jobs:
  convert:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup sing-box (pre-release)
      run: |
        LATEST_PRE_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases | jq -r '[.[] | select(.prerelease == true)][0].tag_name')
        echo "Latest sing-box pre-release version: $LATEST_PRE_VERSION"
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_PRE_VERSION}/sing-box-${LATEST_PRE_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_PRE_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_PRE_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version
    - name: Compile Emby JSON to SRS
      run: |
        if [ -f emby.json ]; then
          sing-box rule-set compile --output emby.srs emby.json
          echo "Emby JSON compiled to SRS"
        else
          echo "emby.json not found, skipping Emby conversion"
        fi
    - name: Download and merge AdGuard filters
      run: |
        combined_filters="combined_adguard_filters.txt"
        > $combined_filters  # 创建一个空文件
        filters=(
          "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt"
          "https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockfilters.txt"
        )
        
        for filter in "${filters[@]}"; do
          wget -O - "$filter" >> $combined_filters || echo "下载 $filter 失败，继续"
        done
    - name: Add user rules
      run: |
        cat << EOF >> combined_adguard_filters.txt
        @@||lanzouw.com^
        @@||statics.123pan.com^
        @@||a0.app.xiaomi.com^
        @@||cn.app.chat.xiaomi.net^
        @@||resolver.msg.xiaomi.net^
        @@||t.co^
        @@||click.taobao.com^
        @@||uland.taobao.com^
        @@||emby.imetyou.top^
        @@||emby.pilipiliultra.top^
        @@||knicks.jd.com^
        EOF
    - name: Convert combined AdGuard filters to SRS
      run: |
        sing-box rule-set convert --type adguard --output adg-dns.srs combined_adguard_filters.txt
        echo "AdGuard filters converted to SRS"
    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Create SRS to JSON converter script
      run: |
        cat > srs_to_json.py << EOL
        ${{ steps.srs_to_json_script.outputs.content }}
        EOL
    - name: Convert SRS files to JSON
      run: |
        for srs_file in *.srs; do
          json_file="${srs_file%.srs}.json"
          python srs_to_json.py "$srs_file" "$json_file"
          echo "Converted $srs_file to $json_file"
          echo "First few lines of $json_file:"
          head -n 10 "$json_file"
        done
    - name: Verify JSON content
      run: |
        for json_file in *.json; do
          if [ -f "$json_file" ]; then
            if ! jq empty "$json_file" 2>/dev/null; then
              echo "Error: $json_file is not a valid JSON file"
              cat "$json_file"
              exit 1
            else
              echo "$json_file is a valid JSON file"
            fi
          else
            echo "$json_file not found"
            exit 1
          fi
        done
    - name: Commit and push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.srs *.json srs_to_json.py
        git commit -m "Convert Emby JSON and AdGuard filters to SRS and JSON" || echo "No changes to commit"
        git push
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: sing-box-rule-sets
        path: |
          *.srs
          *.json
          srs_to_json.py
