name: Update DNS and Emby Rule

on:
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  update-rules:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Download and process rules
      run: |
        # 下载 adblockdns.txt 文件并仅提取白名单域名
        curl -o adblockdns.txt https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdns.txt
        grep '^@@||' adblockdns.txt | sed 's/^@@||//; s/\^$//' | sort -u > new_whitelist.txt

        # 合并新旧 whitelist 并去重
        cat whitelist.txt new_whitelist.txt | sort -u | sed '/^$/d' > temp_whitelist.txt
        mv temp_whitelist.txt whitelist.txt

        # 下载 AWAvenue-Ads-Rule-Singbox.json 文件
        curl -o awavenue_ads_rule_singbox.json https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox-regex.json

        # 清理 JSON 文件中的注释并修改版本号
        sed '/^\/\/.*$/d' awavenue_ads_rule_singbox.json | 
        sed 's/"version": 1,/"version": 2,/' > awavenue_ads_rule_clean.json

        # 从域名列表中删除 whitelist.txt 中的域名，并添加 block.txt 中的域名
        jq --arg whitelist "$(cat whitelist.txt | paste -sd "|" -)" \
           --slurpfile blocklist <(sed 's/^/"/; s/$/",/' block.txt | sed '$ s/,$//' | sed '1i[' | sed '$a]') '
          .rules[0].domain |= (
            . - (. | map(select(test($whitelist)))) + 
            $blocklist[0]
          ) | unique | sort
        ' awavenue_ads_rule_clean.json > adg-dns.json

    - name: Debug adg-dns.json
      run: jq '.' adg-dns.json

    - name: Setup sing-box (pre-release)
      run: |
        LATEST_PRE_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases | jq -r '[.[] | select(.prerelease == true)][0].tag_name')
        echo "Latest sing-box pre-release version: $LATEST_PRE_VERSION"
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_PRE_VERSION}/sing-box-${LATEST_PRE_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_PRE_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_PRE_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Convert adg-dns.json to adg-dns.srs
      run: |
        sing-box rule-set compile --output adg-dns.srs adg-dns.json

    - name: Convert emby.json to emby.srs
      run: |
        sing-box rule-set compile --output emby.srs emby.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add whitelist.txt adg-dns.json adg-dns.srs
        git commit -m "Update DNS rules" || echo "No changes to commit"
        git push
