name: Update adg-awa Rule

on:
  schedule:
    - cron: "15 0,8,16 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq wget tar

    - name: Download base JSON
      run: |
        curl -o AWAvenue.json https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json

    - name: Process block and noblock domains in JSON
      run: |
        # 读取 block.txt 和 noblock.txt 中的域名，并将其转换为 jq 格式
        block_domains=$(jq -R -s -c 'split("\n")[:-1]' block.txt)
        noblock_domains=$(jq -R -s -c 'split("\n")[:-1]' noblock.txt)

        # 从原始 JSON 中删除 noblock.txt 的域名
        jq --argjson noblock "$noblock_domains" '
          .rules[0].domain |= map(select(. as $d | $noblock | index($d) | not)) |
          .rules[0].domain_keyword |= map(select(. as $d | $noblock | index($d) | not)) |
          .rules[0].domain_suffix |= map(select(. as $d | $noblock | index($d) | not))
        ' AWAvenue.json > cleaned_awa.json

        # 将 block.txt 中的域名加入到 "domain" 部分
        jq --argjson block "$block_domains" '
          .rules[0].domain += $block
        ' cleaned_awa.json > updated_awa.json

        # 对所有数组进行去重并按字母排序
        jq '
          .rules[0].domain |= unique | sort |
          .rules[0].domain_keyword |= unique | sort |
          .rules[0].domain_suffix |= unique | sort
        ' updated_awa.json > adg-awa.json

        # 确认输出有效 JSON
        jq . adg-awa.json

    - name: Setup sing-box
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_VERSION}/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Convert JSON to SRS
      run: |
        sing-box rule-set compile --output adg-awa.srs adg-awa.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add final_awa.json final_awa.srs
        git commit -m "Update custom rules with block domains, remove noblock domains, and generate SRS" || echo "No changes to commit"
        git push
