name: Update adg-dns-lite Rule

on: 
  schedule:
    - cron: "30 0,8,16 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq wget tar

    - name: Download base JSON
      run: |
        curl -o adblocksingboxlite.json https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblocksingboxlite.json

    - name: Process domains (remove noblock + add block + dedup + sort)
      run: |
        # 读取 noblock.txt 和 block.txt
        noblock=$(jq -R -s -c 'split("\n")[:-1]' noblock.txt)
        block=$(jq -R -s -c 'split("\n")[:-1]' block.txt)

        jq --argjson noblock "$noblock" --argjson block "$block" '
          .rules[0].domain_suffix |= (
            # 1. 去掉 noblock 里的域名
            map(select(. as $d | $noblock | index($d) | not))
            # 2. 追加 block 里的域名
            + $block
            # 3. 去重
            | unique
            # 4. 按字母顺序排序
            | sort
          )
        ' adblocksingboxlite.json > adg-dns-lite.json

        # 确认输出 JSON 格式
        jq . adg-dns-lite.json

    - name: Setup sing-box
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_VERSION}/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Convert JSON to SRS
      run: |
        sing-box rule-set compile --output adg-dns-lite.srs adg-dns-lite.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add adg-dns.json adg-dns.srs
        git commit -m "Update adg-dns.json and adg-dns.srs" || echo "No changes to commit"
        git push
