name: Update adg-dns-lite Rule

on: 
  schedule:
    - cron: "30 0,8,16 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai  

jobs:
  update-rules-lite:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Download and process lite rules
      run: |
        FILES_LITE=()
        curl -o adblockdnslite.txt https://raw.githubusercontent.com/217heidai/adblockfilters/main/rules/adblockdnslite.txt
        FILES_LITE+=("adblockdnslite.txt")
        curl -o awavenue_ads_rule_singbox.json https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox-regex.json

        sed '/^\/\/.*$/d' awavenue_ads_rule_singbox.json > awavenue_ads_rule_clean.json

        if ! jq empty awavenue_ads_rule_clean.json; then
          echo "Error: Invalid JSON format in awavenue_ads_rule_clean.json"
          exit 1
        fi

        jq -r '.rules[].domain[]' awavenue_ads_rule_clean.json > extracted_domains_lite.txt || true
        FILES_LITE+=("extracted_domains_lite.txt")
        cat "${FILES_LITE[@]}" > combined_rules_lite.txt

        grep '^\|\|' combined_rules_lite.txt | sed '/^!/d; s/^||//; s/\^$//' | sort -u | sed '/^$/d' > new_blacklist_lite.txt

        cat new_blacklist_lite.txt block.txt | sort -u | sed '/^$/d' > temp_blacklist_lite.txt
        mv temp_blacklist_lite.txt blacklist-lite.txt

        grep -vxFf whitelist.txt blacklist-lite.txt > temp_blacklist_lite.txt
        mv temp_blacklist_lite.txt blacklist-lite.txt

        sed -i '/^@@/d' blacklist-lite.txt
        
        LC_ALL=C sort -u -o blacklist-lite.txt blacklist-lite.txt
        LC_ALL=C sort -u -o block.txt block.txt
        touch blacklist-lite.txt block.txt

    - name: Create adg-dns-lite.json
      run: |
        if ! domain_regex_raw=$(jq -r '.rules[0].domain_regex' awavenue_ads_rule_clean.json); then
          echo "Error: Failed to extract domain_regex"
          exit 1
        fi
        
        if ! echo "$domain_regex_raw" | jq empty; then
          echo "Error: Invalid domain_regex JSON format"
          exit 1
        fi
        
        {
          echo '{
            "version": 3,
            "rules": [
              {
                "domain_suffix": ['
          
          sed 's/.*/"&",/' blacklist-lite.txt | sed '/^""$/d; /^"@@/d' | sed '$ s/,$//'
          
          echo '                ],'
          echo '                "domain_regex":'
          echo "$domain_regex_raw"
          echo '              }'
          echo '            ]'
          echo '          }'
        } > temp_adg-dns-lite.json
        
        if ! jq empty temp_adg-dns-lite.json; then
          echo "Error: Invalid final JSON format"
          exit 1
        fi
        
        jq . temp_adg-dns-lite.json > adg-dns-lite.json
        rm temp_adg-dns-lite.json

    - name: Debug adg-dns-lite.json
      run: |
        echo "Validating final JSON format..."
        if ! jq empty adg-dns-lite.json; then
          echo "Error: Invalid JSON in final file"
          exit 1
        fi
        echo "Final file content:"
        cat adg-dns-lite.json

    - name: Setup sing-box (release)
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
        echo "Latest sing-box version: $LATEST_VERSION"
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_VERSION}/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Convert adg-dns-lite.json to adg-dns-lite.srs
      run: |
        sing-box rule-set compile --output adg-dns-lite.srs adg-dns-lite.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add blacklist-lite.txt adg-dns-lite.json adg-dns-lite.srs
        git commit -m "Force update DNS lite rules with sorted files" || echo "No changes to commit"
        git push
