name: Update adg-awa Rule

on:
  schedule:
    - cron: "15 0,8,16 * * *"
  workflow_dispatch:

env:
  TZ: Asia/Shanghai

jobs:
  update-rules:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y jq wget tar

    - name: Download base JSON
      run: |
        curl -o AWAvenue.json https://raw.githubusercontent.com/TG-Twilight/AWAvenue-Ads-Rule/main/Filters/AWAvenue-Ads-Rule-Singbox.json

    - name: Process block and noblock domains in JSON
      run: |
        block_domains=$(jq -R -s -c 'split("\n")[:-1]' block.txt)
        noblock_domains=$(jq -R -s -c 'split("\n")[:-1]' noblock.txt)

        jq --argjson noblock "$noblock_domains" '
          .rules[0].domain |= map(select(. as $d | $noblock | index($d) | not)) |
          .rules[0].domain_keyword |= map(select(. as $d | $noblock | index($d) | not)) |
          .rules[0].domain_suffix |= map(select(. as $d | $noblock | index($d) | not))
        ' AWAvenue.json > cleaned_awa.json

        jq --argjson block "$block_domains" '
          .rules[0].domain += $block
        ' cleaned_awa.json > updated_awa.json

        jq '
          .rules[0].domain = (if .rules[0].domain | length > 0 then .rules[0].domain | unique | sort else .rules[0].domain end) |
          .rules[0].domain_keyword = (if .rules[0].domain_keyword | length > 0 then .rules[0].domain_keyword | unique | sort else .rules[0].domain_keyword end) |
          .rules[0].domain_suffix = (if .rules[0].domain_suffix | length > 0 then .rules[0].domain_suffix | unique | sort else .rules[0].domain_suffix end)
        ' updated_awa.json > adg-awa.json

        jq . adg-awa.json

    - name: Setup sing-box
      run: |
        LATEST_VERSION=$(curl -s https://api.github.com/repos/SagerNet/sing-box/releases/latest | jq -r .tag_name)
        wget https://github.com/SagerNet/sing-box/releases/download/${LATEST_VERSION}/sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        tar -xzvf sing-box-${LATEST_VERSION#v}-linux-amd64.tar.gz
        sudo mv sing-box-${LATEST_VERSION#v}-linux-amd64/sing-box /usr/local/bin/
        sing-box version

    - name: Convert JSON to SRS
      run: |
        sing-box rule-set compile --output adg-awa.srs adg-awa.json

    - name: Commit and push changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add adg-awa.json adg-awa.srs
        git commit -m "Update adg-awa rules" || echo "No changes to commit"
        git push
